# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "fedora/31-cloud-base"
  config.vm.box_version = "31.20191023.0"
  config.vm.hostname = "yetus"

  config.vm.define :yetus do |yetus|
    yetus.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
    end
  end
end
